Add Mobile main menu and about section
basirking/Capstone pull request #1
Opened 2022-05-23 20:38 UTC by basirking

2022-05-26 21:19 UTC, ShadyShawkat requested changes
## Hi @basirking, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 21:19 UTC, ShadyShawkat commented on README.md
> +- etc
- [x] Kindly edit the "Acknowledgements" section to give appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/).
![image](https://user-images.githubusercontent.com/24703171/169136139-8b2f189e-28e2-4ef7-9fec-68827d018b84.png)

2022-05-26 21:19 UTC, ShadyShawkat commented on index.html
> +  </div>
- [x] Kindly edit this section's header text to have the appropriate text size to match the original design.

| | Your design | Original design |
| --- | --- | --- |
| Desktop | ![image](https://user-images.githubusercontent.com/62290545/170573986-a1a581ce-7a77-4e2e-8724-e0d182e699bd.png) | ![image](https://user-images.githubusercontent.com/62290545/170574166-7406a870-b131-4a1e-805f-c5fd16476aa3.png) |
| Mobile | ![image](https://user-images.githubusercontent.com/62290545/170574676-b0978656-6e93-48f2-93cf-4577969b64c3.png) | ![image](https://user-images.githubusercontent.com/62290545/170575023-b3a4aef4-b18f-4125-88e2-a95249c66662.png) |

2022-05-26 21:19 UTC, ShadyShawkat commented on index.html
> +    </div>
- [x] Please make sure that the cards in this section on mobile view, don't take more width than they should which causes the UI to break.
- [x] Kindly adjust the left and right spacing of this section to match the original design.

| Your design | Original design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/62290545/170575777-2e76d8ee-09e9-4ccc-be96-95ed04158504.png) | ![image](https://user-images.githubusercontent.com/62290545/170575851-17076135-e144-4170-9758-557723281451.png) |

2022-05-26 21:19 UTC, ShadyShawkat commented on index.html
> +</section>
- [x] Kindly align the featured speakers cards to better match the original design. (You can use a grid which would make the cards align better).
- [ ] Please add the checkered background image added to the top left side of each speaker image. (You can set it as a background image and control its position and size using the `background-position` and `background-size` properties).

| Your design | Original design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/62290545/170576545-8c068e52-5532-41bf-8f48-5ec3c0501ebb.png) | ![image](https://user-images.githubusercontent.com/62290545/170576598-6697bb8b-e415-4aca-b7f8-417fcfab94cc.png) |

2022-05-26 21:19 UTC, ShadyShawkat commented on index.html
> +          <li ><a class="link about"  href="#">About</a></li>
- [ ] Kindly edit this link to redirect the user to the "about" page.
- [ ] Please add a way to navigate from the "about" page to the "home" page on the mobile view. (You can add a navlink in the mobile menu that navigates to the home page)

- [ ] Kindly adjust the size of the mobile menu to take 100% of the screen's height, to make your project more responsive. 
![image](https://user-images.githubusercontent.com/62290545/170580457-0927c8ee-411b-456c-8ec1-aba11c5c46c5.png)

2022-05-26 21:19 UTC, ShadyShawkat commented on about.html
> +
- [ ] Kindly edit this section's header text to have the appropriate size and spacing around it to match the original design.

| | Your design | Original design |
| --- | --- | --- |
| Desktop | ![image](https://user-images.githubusercontent.com/62290545/170581304-e29b38ae-de8f-4c68-be2c-297a3fc7c356.png) | ![image](https://user-images.githubusercontent.com/62290545/170581352-02ccdb6d-9f24-44cc-8028-6c6d707ee202.png) |
| Mobile | ![image](https://user-images.githubusercontent.com/62290545/170581406-ab761c7b-c3de-4b25-9db1-6fdb48874a98.png) | ![image](https://user-images.githubusercontent.com/62290545/170581455-42f829a7-d0a5-4ef2-b383-1ddc9ab08c2d.png) |

2022-05-26 21:19 UTC, ShadyShawkat commented on README.md
> +
- [ ] Please change the project's title to better suit your project.

2022-05-27 08:30 UTC, OmarRamoun approved these changes
# 🟢 Capstone Approved! 🏁🏆🎉

## Hi @basirking 👋

In my opinion, Your project is complete! ✔️ 🏁 and ready for the presentation!.

Finally, **you did it**! 🎉 👏. You have completed your first 1️⃣ 🥇 cpastone in microverse. Your code was very professional 💯 and I can see you have a great chance to be a Great Software Engineer ⛑️.

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉. And Welcome to Microverse 👋.

> **Note:** You can now take a break even if short before you move on to the next module. Happy 😄 Coding 🖥️! and Have a nice day 🌞.

## Highlights 🌟

- ✔️ descriptive commit messages 
- ✔️ descriptive PR title and description
- ✔️ no linter errors
- ✔️ implemented the previous review requested changes
- The code is top-notch! 💯 and has a huge potential.

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@omarramoun](https://img.shields.io/github/followers/omarramoun?label=Ramoun&style=social)](https://github.com/omarramoun)
- This is My **Twitter**: [![@omarramoun](https://img.shields.io/twitter/follow/omarramoun?label=ramoun16&style=social)](https://twitter.com/omarramoun)
- This is My **Slack**: [![Ramoun](https://img.shields.io/badge/slack-@Ramoun-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-27 08:34 UTC, merged